@startuml
'https://plantuml.com/object-diagram
skinparam linetype ortho

object "<u>:GenerateIdeaCommand" as GenerateIdeaCommand #lightgreen

object "<u>randomFood:Food" as Food #lightblue
Food : description = "Zen Zen Sushi"

object "<u>randomActivity:Activity" as Activity #salmon
Activity : description = "Haji Lane Shopping"

object "<u>:Idea" as Idea #orchid

GenerateIdeaCommand -- Idea

Idea -[norank]-> Food : dining option
Idea -[norank]-> Activity : activity

@enduml
