@startuml
'https://plantuml.com/sequence-diagram
hide footbox

actor User as User
participant ":Ui" as Ui
participant ":GenerateIdeaCommand" as GenerateIdeaCommand
participant ":FoodList" as FoodList
participant ":ActivityList" as ActivityList
participant ":Idea" as Idea
participant ":Storage" as Storage

User -> Ui: idea
activate Ui
Ui -> GenerateIdeaCommand: GenerateIdeaCommand()
activate GenerateIdeaCommand

loop userSatisfied != yes
    GenerateIdeaCommand -> FoodList: getRandomFood()
    activate FoodList
    FoodList --> GenerateIdeaCommand
    deactivate FoodList

    GenerateIdeaCommand -> ActivityList: getRandomActivity()
    activate ActivityList
    ActivityList --> GenerateIdeaCommand
    deactivate ActivityList

    GenerateIdeaCommand -> Idea: Idea(Food, Activity)
    activate Idea
    Idea --> GenerateIdeaCommand:
    deactivate Idea
    GenerateIdeaCommand --> Ui:
    deactivate GenerateIdeaCommand
    Ui --> User: printIdea()
    deactivate Ui
end

User -> Ui: yes
activate Ui
Ui -> GenerateIdeaCommand: yes
activate GenerateIdeaCommand
GenerateIdeaCommand -> Storage: saveFood(foods)
activate Storage
Storage --> GenerateIdeaCommand
deactivate Storage
GenerateIdeaCommand -> Storage: saveActivity(activities)
activate Storage
Storage --> GenerateIdeaCommand
deactivate Storage
GenerateIdeaCommand --> Ui:
deactivate GenerateIdeaCommand
destroy GenerateIdeaCommand
Ui --> User: printDoneMessage()
deactivate Ui

@enduml