@startuml
'https://plantuml.com/sequence-diagram

actor User
participant "Ui" as UI
participant "Parser" as P
participant "GenerateGiftCommand" as GGC
participant "GiftList" as GL
participant "Gift" as G
participant "Storage" as S

User -> UI : gift
UI -> P : parseCommand(userInput, userDetails)
P -> GGC : new GenerateGiftCommand()
activate GGC

loop until user is satisfied
GGC -> GL : getRandomGift()
GL -> G : select random
G --> GL : return gift
GL --> GGC : return gift
GGC --> UI : display gift suggestion
UI -> User : show gift and ask "Satisfied with the gift suggestion? [Yes/No]"
User -> UI : no
UI -> GGC : continue
end

User -> UI : yes
UI -> GGC : user satisfied
GGC -> G : markComplete()
GGC -> S : saveGift(gifts)
deactivate GGC
@enduml
